"""extend order table

Revision ID: 0c001b07d538
Revises: f1814788aa62
Create Date: 2022-08-17 13:46:11.885830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c001b07d538'
down_revision = 'f1814788aa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('racket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'rackets', ['racket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'racket_id')
    # ### end Alembic commands ###
