"""redesign order model

Revision ID: 28a0da3f6c99
Revises: 2a7f1e67ec40
Create Date: 2022-08-18 09:55:41.873478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a0da3f6c99'
down_revision = '2a7f1e67ec40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ownership_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_racket_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'racket_ownerships', ['ownership_id'], ['id'])
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'racket_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('racket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_racket_id_fkey', 'orders', 'rackets', ['racket_id'], ['id'])
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'ownership_id')
    # ### end Alembic commands ###
