"""add done to orders

Revision ID: 2a7f1e67ec40
Revises: b3d0a260366a
Create Date: 2022-08-17 13:56:00.643369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7f1e67ec40'
down_revision = 'b3d0a260366a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'done')
    # ### end Alembic commands ###
