"""initial_schema

Revision ID: 2f6ba46d8d60
Revises: 
Create Date: 2025-04-26 22:19:30.431093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6ba46d8d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('plz', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('skips_head', sa.String(), nullable=True),
    sa.Column('skips_tail', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('gauge', sa.String(length=10), nullable=False),
    sa.Column('length', sa.String(length=3), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('structure', sa.String(length=20), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('consumption', sa.String(length=5), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racket_ownerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customers_id', sa.Integer(), nullable=True),
    sa.Column('rackets_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customers_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rackets_id'], ['rackets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('hybrid', sa.Boolean(), nullable=True),
    sa.Column('string_main_id', sa.Integer(), nullable=True),
    sa.Column('string_cross_id', sa.Integer(), nullable=True),
    sa.Column('tension_main', sa.String(length=5), nullable=False),
    sa.Column('tension_cross', sa.String(length=5), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ownership_id'], ['racket_ownerships.id'], ),
    sa.ForeignKeyConstraint(['string_cross_id'], ['strings.id'], ),
    sa.ForeignKeyConstraint(['string_main_id'], ['strings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('racket_ownerships')
    op.drop_table('strings')
    op.drop_table('rackets')
    op.drop_table('customers')
    # ### end Alembic commands ###
