"""Add customer-racket relation

Revision ID: 3e926e03f051
Revises: d963105a233d
Create Date: 2022-08-12 13:08:08.948225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e926e03f051'
down_revision = 'd963105a233d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_racket',
    sa.Column('customers_id', sa.Integer(), nullable=True),
    sa.Column('rackets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customers_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rackets_id'], ['rackets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_racket')
    # ### end Alembic commands ###
