"""merge user and customer models

Revision ID: 3f881ba62f61
Revises: 3f7ba46d8d70
Create Date: 2025-05-01 13:49:30.320581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f881ba62f61'
down_revision = '3f7ba46d8d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('customers', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('customers', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('customers', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('customers', 'is_admin')
    op.drop_column('customers', 'password_hash')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='users_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
