"""add strings to order

Revision ID: 5c7ccfc25313
Revises: 28a0da3f6c99
Create Date: 2022-08-21 16:51:33.136460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7ccfc25313'
down_revision = '28a0da3f6c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('hybrid', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('string_main_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('string_cross_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'strings', ['string_main_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'strings', ['string_cross_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'string_cross_id')
    op.drop_column('orders', 'string_main_id')
    op.drop_column('orders', 'hybrid')
    # ### end Alembic commands ###
