"""Add date_added to rackets

Revision ID: 7463c3644b99
Revises: 3e926e03f051
Create Date: 2022-08-12 13:11:13.389840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7463c3644b99'
down_revision = '3e926e03f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rackets', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rackets', 'date_added')
    # ### end Alembic commands ###
