"""fix datetime

Revision ID: b3d0a260366a
Revises: 0c001b07d538
Create Date: 2022-08-17 13:53:22.134033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d0a260366a'
down_revision = '0c001b07d538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('racket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'rackets', ['racket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'racket_id')
    # ### end Alembic commands ###
