"""Initial Migration

Revision ID: d963105a233d
Revises: 
Create Date: 2022-08-12 09:53:21.335035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd963105a233d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('skips_head', sa.String(), nullable=True),
    sa.Column('skips_tail', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rackets')
    # ### end Alembic commands ###
