"""Add password reset token fields

Revision ID: f9f72b9b4b06
Revises: 3f881ba62f61
Create Date: 2025-05-01 14:40:32.972031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f72b9b4b06'
down_revision = '3f881ba62f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['reset_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'reset_token_expiration')
    op.drop_column('customers', 'reset_token')
    # ### end Alembic commands ###
